### ISSUE TITLE
Add support for comma-free color syntaxes

### ISSUE THREAD

**Issue by oranj** [donatj/AlikeColorFinder#1]
Modern browsers support comma-free rgb syntaxes, which `AlikeColorFinder` chokes on.

See [here](https://css-tricks.com/no-comma-color-functions-in-css/)

I'm getting the error: 

```
Error: rgb(255 150 150): Invalid param count
```

Because this line (CssColorExtractor.php:198) only explodes based on commas:

```
$params = array_map('\floatval', array_map('\trim', explode(',', $result['params'])));
```

**Comment by donatj** [comment]
Oh, interesting and eww. Is what it is I guess.

Time to spruce up the ol' color extractor some it seems.

**Comment by donatj** [comment]
This is done and released ;)
